services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    working_dir: /app
    container_name: churnguard-mlflow
    volumes:
      - ./:/app
      - mlruns_data:/app/mlruns
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:///mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
        --serve-artifacts
    healthcheck:
      test: ["CMD", "curl", "-f","python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000')"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 20s
    ports:
      - "5000:5000"
    networks:
      - churnguard_net

  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churnguard-trainer
    command: python churnguard/train.py
    volumes:
      - ./data:/app/data:ro
      - ./churnguard:/app/churnguard:ro
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - churnguard_net
    restart: "no"
    

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churnguard-api  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=churnguard
      - MODEL_URI=models:/churnguard/Production
      - MODEL_STAGE=Production
    depends_on:
      mlflow:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - churnguard_net
    restart: unless-stopped  

volumes:
  mlruns_data:
    driver: local

networks:
  churnguard_net:
    driver: bridge
